server:
  port: 3344

spring:
  application:
    name: microservice-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lrh007/microservice-cloud-config.git #git仓库地址