server:
  port: 80
spring:
  application:
    name: microservice-cloud-consumer
eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: false #自己不用注册服务
